Repository unb-mds/2024-1-forUnB, pull requests merged in 2024-08, with the labels that each got.

#110 73 correcao da pagina de login
  forunb/main/views.py
  forunb/users/templates/users/register_unb_email.html
  forunb/users/urls.py
  forunb/users/views.py
Labels: bug, front-end, back-end

#120 119 refatoracao do codigo
  forunb/main/templates/accounts/login.html
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/forums.html
  forunb/main/templates/main/index.html
  forunb/main/templates/main/new_answer.html
  forunb/main/templates/main/new_question.html
  forunb/main/templates/main/question_detail.html
  forunb/main/templates/main/questions.html
  forunb/main/tests/test_url.py
  forunb/main/tests/test_views.py
  forunb/main/urls.py
  forunb/main/views.py
  forunb/search/urls.py
  forunb/templates/base.html
  forunb/templates/registration/login.html
  forunb/users/templates/users/login.html
  forunb/users/templates/users/register.html
  forunb/users/templates/users/register_unb_email.html
  forunb/users/urls.py
  forunb/users/views.py
Labels: front-end, back-end

#123 104 pagina home
  forunb/main/templates/main/index.html
  forunb/main/templatetags/custom_filters.py
  forunb/static/css/styles.css
Labels: front-end

#126 125 criar feature de modo anônimo para posts
  forunb/main/forms.py
  forunb/main/migrations/0004_answer_is_anonymous_question_is_anonymous.py
  forunb/main/models.py
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/index.html
  forunb/main/templates/main/question_detail.html
Labels: back-end

#124 122 criar feature de dar follow e unfollow nos foruns
  forunb/main/templates/main/forum_detail.html
  forunb/main/urls.py
  forunb/main/views.py
  forunb/templates/base.html
  forunb/users/admin.py
Labels: back-end

#121 115 aperfeicoamento da barra de pesquisa
  forunb/search/views.py
  forunb/static/css/styles.css
  forunb/templates/base.html
Labels: back-end

#129 feat: adding logo and name to the website
  forunb/static/forunb/img/logo_favicon.png
  forunb/templates/base.html
Labels: front-end

#128 90 ajeitar pequenos detalhes
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/forums.html
  forunb/main/templates/main/question_detail.html
  forunb/static/css/styles.css
  forunb/templates/base.html
Labels: front-end

#130 127 criando página de meus posts
  forunb/main/templates/main/questions.html
  forunb/main/urls.py
  forunb/main/views.py
  forunb/templates/base.html
  forunb/users/admin.py
Labels: back-end

#135 ci: creating deploy action
  .github/workflows/docs.yml
Labels: documentation, devops, ci

#142 139 adicionar ata da sprint 8 na documentacao
  docs/sprints/sprint8.md
  mkdocs.yml
Labels: documentation

#143 Estudo
  docs/sprints/sprint8.md
  mkdocs.yml
Labels: documentation

#144 138 feature de delecao de posts
  forunb/main/templates/main/confirm_delete.html
  forunb/main/templates/main/question_detail.html
  forunb/main/templates/main/questions.html
  forunb/main/urls.py
  forunb/main/views.py
Labels: back-end

#151 145 feature de edicao e visualizacao de perfil
  forunb/templates/base.html
  forunb/users/forms.py
  forunb/users/templates/users/profile.html
  forunb/users/urls.py
  forunb/users/views.py
Labels: enhancement, back-end

#154 152 feature de notificacao para o usuario
  forunb/main/migrations/0005_alter_answer_description_alter_answer_is_anonymous_and_more.py
  forunb/main/models.py
  forunb/main/templates/main/notifications.html
  forunb/main/urls.py
  forunb/main/views.py
  forunb/templates/base.html
Labels: back-end

#153 149 aperfeicoamento da barra de pesquisa back
  forunb/main/tests/test_views.py
  forunb/search/views.py
  requirements.txt
Labels: back-end

#161 159 feature de upload de imagens em foto de perfil e posts
  forunb/forunb/settings.py
  forunb/forunb/urls.py
  forunb/main/forms.py
  forunb/main/migrations/0006_answer_image_question_image.py
  forunb/main/migrations/0007_alter_answer_image_alter_question_image.py
  forunb/main/models.py
  forunb/main/templates/main/new_question.html
  forunb/main/templates/main/question_detail.html
  forunb/main/tests/test_views.py
  forunb/main/views.py
  forunb/users/forms.py
  forunb/users/migrations/0004_customuser_photo.py
  forunb/users/migrations/0005_alter_customuser_photo.py
  forunb/users/models.py
  forunb/users/templates/users/profile.html
  forunb/users/views.py
  requirements.txt
Labels: back-end

#163 146 incrementar o upvote 1
  forunb/main/migrations/0008_remove_answer_upvotes_answer_upvoters_and_more.py
  forunb/main/models.py
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/index.html
  forunb/main/templates/main/question_detail.html
  forunb/main/tests/test_models.py
  forunb/main/urls.py
  forunb/main/views.py
  forunb/users/admin.py
  forunb/users/migrations/0006_customuser_liked_answers.py
  forunb/users/models.py
Labels: back-end, feature

#167 150 refatoracao da pagina dos meus posts
  forunb/main/templates/main/questions.html
Labels: front-end

#166 118 aperfeicoamento visual da barra de pesquisa
  forunb/search/views.py
  forunb/static/css/styles.css
  forunb/templates/base.html
Labels: front-end

#165 147 incrementar um filtro para foruns 1
  forunb/main/templates/main/forum_detail.html
  forunb/main/views.py
  forunb/users/views.py
Labels: back-end, feature

#168 style : adding "fale conosco" in the home page
  forunb/templates/base.html
Labels: front-end

#170 131 aperfeicoamento das paginas de login e cadastro
  forunb/main/migrations/0005_alter_answer_description_alter_answer_is_anonymous_and_more.py
  forunb/users/forms.py
  forunb/users/templates/users/login.html
  forunb/users/templates/users/register_unb_email.html
  forunb/users/views.py
Labels: bug, front-end

#171 160 feature de teclado matemática para perguntas e respostas 1
  forunb/main/forms.py
  forunb/main/templates/main/new_question.html
  forunb/main/templates/main/question_detail.html
  forunb/main/views.py
  forunb/templates/base.html
Labels: back-end, feature

#169 164 criar feature de denúncia de perguntas e respostas
  forunb/main/admin.py
  forunb/main/forms.py
  forunb/main/migrations/0009_report.py
  forunb/main/migrations/0010_report_answer_alter_report_question.py
  forunb/main/models.py
  forunb/main/templates/main/question_detail.html
  forunb/main/urls.py
  forunb/main/views.py
Labels: back-end, feature

#175 Estudo
  docs/sprints/sprint9.md
  mkdocs.yml
Labels: documentation

#190 188 preparacao do ambiente para hospedagem
  .github/workflows/CI.yml
  Makefile
  forunb/.env.example
  forunb/forunb/asgi.py
  forunb/forunb/env.py
  forunb/forunb/settings/__init__.py
  forunb/forunb/settings/base.py
  forunb/forunb/settings/local.py
  forunb/forunb/settings/production.py
  forunb/forunb/wsgi.py
  forunb/manage.py
  requirements.txt
  scripts/config.py
Labels: back-end, devops

#195 191 test para users
  .github/workflows/CI.yml
  forunb/users/tests/test_forms.py
  forunb/users/tests/test_urls.py
  forunb/users/tests/test_views.py
  forunb/users/views.py
Labels: back-end, devops, test

#193 192 testes para a main
  forunb/main/tests/test_forms.py
  forunb/main/tests/test_models.py
  forunb/main/tests/test_scraping.py
  forunb/main/tests/test_url.py
  forunb/main/tests/test_views.py
Labels: back-end, test

#198 ci: creating an ci for sonar cloud
  .github/workflows/sonar.yml
  sonar-project.properties
Labels: ci

#202 201 refactor pylint users app
  .github/workflows/pylint.yml
  .github/workflows/sonar.yml
  forunb/users/admin.py
  forunb/users/apps.py
  forunb/users/forms.py
  forunb/users/models.py
  forunb/users/tests/test_forms.py
  forunb/users/tests/test_urls.py
  forunb/users/tests/test_views.py
  forunb/users/urls.py
  forunb/users/views.py
  requirements.txt
  sonar-project.properties
Labels: back-end, devops

#204 203 refactor pylint search app
  .github/workflows/pylint.yml
  forunb/search/admin.py
  forunb/search/apps.py
  forunb/search/models.py
  forunb/search/urls.py
  forunb/search/views.py
Labels: back-end, devops

#205 200 refactor pylint main app
  .github/workflows/pylint.yml
  forunb/main/admin.py
  forunb/main/apps.py
  forunb/main/forms.py
  forunb/main/management/commands/scraping_sigaa.py
  forunb/main/models.py
  forunb/main/scraping.py
  forunb/main/sessions.py
  forunb/main/templatetags/custom_filters.py
  forunb/main/tests/test_forms.py
  forunb/main/tests/test_models.py
  forunb/main/tests/test_scraping.py
  forunb/main/tests/test_url.py
  forunb/main/tests/test_views.py
  forunb/main/urls.py
  forunb/main/views.py
  sonar-project.properties
Labels: back-end, devops, test

#208 191 test para users
  forunb/users/admin.py
  forunb/users/tests/test_forms.py
  forunb/users/tests/test_models.py
  forunb/users/tests/test_urls.py
  forunb/users/tests/test_views.py
  forunb/users/views.py
Labels: back-end, test

#210 209 documentacao do codigo
  .github/COMMIT_TEMPLATE/README.md
  .github/workflows/README.md
Labels: documentation

#214 docs: updating readme
  README.md
Labels: documentation

#216 177 estilizacao da pagina perfil
  forunb/users/templates/users/profile.html
Labels: front-end

#218 179 estilizacao de denúncia
  forunb/main/templates/main/question_detail.html
Labels: front-end

#215 181 filtro para os foruns
  forunb/main/templates/main/index.html
  forunb/main/tests/test_views.py
  forunb/main/views.py
Labels: back-end, feature

#221 176 estilizacao do filtro
  forunb/main/templates/main/forum_detail.html
Labels: front-end

#223 docs: script docs
  scripts/README.md
Labels: documentation

#225 docs: updating readme
  README.md
Labels: documentation

#228 227 fixing runserver issue
  forunb/forunb/settings/__init__.py
  forunb/forunb/settings/base.py
  forunb/forunb/settings/local.py
  forunb/forunb/settings/production.py
Labels: bug, back-end

#229 226 new readme
  forunb/forunb/README.md
  forunb/main/README.md
  forunb/main/management/commands/README.md
  forunb/search/README.md
  forunb/users/README.md
Labels: documentation

#232 230 updating mkdocs
  docs/scraping/documentacao.md
  docs/sprints/sprint10.md
  mkdocs.yml
Labels: documentation

#231 217 ajeitar criação de perguntas e respostas
  forunb/main/templates/main/new_question.html
Labels: front-end

#234 183 resolver o bug do upvote
  forunb/users/admin.py
  forunb/users/forms.py
Labels: bug, back-end

#237 236 fixing code for heroku deployment
  Procfile
  forunb/forunb/asgi.py
  forunb/forunb/env.py
  forunb/forunb/settings/base.py
  forunb/forunb/settings/local.py
  forunb/forunb/wsgi.py
  forunb/manage.py
  procfile
  requirements.txt
Labels: devops

#242 fix: Fixing static's path bug
  forunb/forunb/settings/base.py
Labels: bug, back-end

#235 180 detalhes 1
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/index.html
  forunb/main/templates/main/new_question.html
  forunb/main/templates/main/notifications.html
  forunb/main/templates/main/question_detail.html
  forunb/main/templates/main/questions.html
  forunb/static/css/styles.css
  forunb/static/forunb/img/default.jpg
  forunb/static/forunb/img/logo3.jpg
  forunb/templates/base.html
  forunb/users/templates/users/login.html
  forunb/users/templates/users/profile.html
  forunb/users/templates/users/register_unb_email.html
Labels: front-end, UI/UX

#243 239 migracao do banco de dados para postgresql-1
  .github/workflows/CI.yml
  .github/workflows/sonar.yml
  forunb/forunb/settings/base.py
  forunb/forunb/settings/local.py
  forunb/forunb/settings/production.py
  forunb/main/migrations/0011_alter_question_author.py
  forunb/main/models.py
  forunb/main/tests/test_views.py
  requirements.txt
Labels: back-end, feature

#244 233 ajeitar resposta de perguntas-1
  forunb/main/forms.py
  forunb/main/templates/main/new_question.html
  forunb/main/templates/main/question_detail.html
  forunb/static/css/styles.css
Labels: front-end

#247 245 simulacao de hospedagem
  .gitignore
  Procfile
  forunb/forunb/settings/base.py
  forunb/forunb/settings/production.py
  forunb/main/models.py
  forunb/main/templates/main/new_question.html
  forunb/main/views.py
  forunb/media/media/answer_images/cropped_image_cJpHPz9.png
  forunb/users/models.py
  requirements.txt
Labels: back-end, devops

#252 251 corrigir problema de storage local de media
  .gitignore
  forunb/forunb/settings/local.py
  forunb/forunb/settings/production.py
  forunb/main/models.py
  forunb/main/templates/main/new_question.html
  forunb/main/templates/main/question_detail.html
  forunb/main/views.py
  forunb/static/css/styles.css
  forunb/static/js/scripts.js
  forunb/templates/base.html
  forunb/users/models.py
  forunb/users/tests/test_models.py
  sonar-project.properties
Labels: bug, back-end

#258 255 atualizar arquitetura e banco de dados
  docs/arquitetura/arquitetura.md
  docs/assets/arquitetura.png
  docs/scraping/scraping.md
  docs/visao_do_produto/visao_produto.md
  mkdocs.yml
Labels: documentation

#260 Estudo
  docs/arquitetura/arquitetura.md
  docs/assets/arquitetura.png
  docs/scraping/scraping.md
  docs/sprints/sprint10.md
  docs/visao_do_produto/visao_produto.md
  mkdocs.yml
Labels: documentation

#262 261 atualizacao das sprints
  docs/index.md
  docs/sprints/roteiro_reunioes.md
  docs/sprints/sprint0.md
  docs/sprints/sprint1.md
  docs/sprints/sprint10.md
  docs/sprints/sprint11.md
  docs/sprints/sprint2.md
  docs/sprints/sprint3.md
  docs/sprints/sprint4.md
  docs/sprints/sprint5.md
  docs/sprints/sprint6.md
  docs/sprints/sprint7.md
  docs/sprints/sprint8.md
  docs/sprints/sprint9.md
  mkdocs.yml
Labels: documentation
