Repository unb-mds/2024-1-forUnB, pull requests merged in 2024-07, with the labels that each got.

#30 docs: implementando git flow
  docs/estudos/gitflow.md
  mkdocs.yml
Labels: documentation

#27 24 bugfix corrigir e integrar a funcao de responder perguntas
  README.md
  backend/backendforum/main/templates/main/new_answer.html
  backend/backendforum/main/templates/main/question.html
  backend/backendforum/main/views.py
  docs/arquitetura/arquitetura.md
  docs/assets/arquitetura.png
  docs/assets/for_unb.png
  docs/index.md
  docs/stylesheets/extra.css
  docs/visao_do_produto/visao_produto.md
  mkdocs.yml
Labels: bug, Back-End

#31 docs: protótipo de alta fidelidade feito no figma
  docs/assets/Calculo_MeusForuns.png
  docs/assets/fazerPergunta.png
  docs/assets/filtro_User.png
  docs/assets/login.png
  docs/assets/responderPergunta.png
  docs/assets/responder_Notificacao.png
  docs/assets/telaInicial.png
  docs/prototipo/prototipo.md
  mkdocs.yml
Labels: documentation

#37 docs: atualizando a visao do prduto
  docs/visao_do_produto/visao_produto.md
Labels: documentation

#35 docs: adicionar ata da sprint 5
  docs/sprints/sprint3.md
  docs/sprints/sprint5.md
  mkdocs.yml
Labels: documentation

#53 refactor: criacao do comentario
  forunb/main/models.py
  forunb/main/views.py
Labels: documentation, Back-End

#55 test: adicionando teste davi
  forunb/main/tests/test_forms.py
Labels: enhancement, Back-End

#58 57 refatoracao do banco de dados
  forunb/forunb/settings.py
  forunb/main/admin.py
  forunb/main/forms.py
  forunb/main/migrations/0002_remove_answer_forum_answer_author_answer_description_and_more.py
  forunb/main/models.py
  forunb/main/templates/accounts/login.html
  forunb/main/templates/main/base.html
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/forums.html
  forunb/main/templates/main/index.html
  forunb/main/templates/main/new_answer.html
  forunb/main/templates/main/new_question.html
  forunb/main/templates/main/question.html
  forunb/main/templates/main/question_detail.html
  forunb/main/templates/main/questions.html
  forunb/main/urls.py
  forunb/main/views.py
  forunb/templates/registration/login.html
  forunb/users/urls.py
Labels: enhancement, Front-End, Back-End

#59 style: melhorar responsividade da página login
  forunb/main/templates/main/base.html
  forunb/static/forunb/img/logo2.jpg
  forunb/templates/registration/login.html
  forunb/users/templates/users/login.html
  forunb/users/templates/users/register_unb_email.html
Labels: Front-End

#60 style: changing elements and responsiviness of home's page
  forunb/main/templates/main/base.html
  forunb/main/templates/main/forums.html
  forunb/main/templates/main/index.html
  forunb/static/css/styles.css
  forunb/users/templates/users/login.html
Labels: Front-End

#77 63 atualizar os requirementstxt
  .github/ISSUE_TEMPLATE/template-para-PullRequest.md
  .github/ISSUE_TEMPLATE/template-para-issues.md
  docs/assets/Calculo_MeusForuns.png
  docs/assets/fazerPergunta.png
  docs/assets/filtro_User.png
  docs/assets/login.png
  docs/assets/responderPergunta.png
  docs/assets/responder_Notificacao.png
  docs/assets/telaInicial.png
  docs/estudos/gitflow.md
  docs/index.md
  docs/prototipo/prototipo.md
  docs/sprints/sprint3.md
  docs/sprints/sprint4.md
  docs/sprints/sprint5.md
  docs/visao_do_produto/visao_produto.md
  mkdocs.yml
  requirements.txt
Labels: documentation, DevOps

#79 66 refazer os testes forms
  forunb/main/tests/test_forms.py
Labels: Back-End

#82 Fixing the forum button redirection
  forunb/main/templates/main/base.html
Labels: bug, Back-End

#78 66 refazer os testes models
  forunb/main/tests/test_models.py
Labels: Back-End

#81 Update README.md
  README.md
Labels: documentation, DevOps

#84 66 refazer os testes views
  forunb/main/tests/test_views.py
Labels: Back-End

#85 Feat: Creating CI.yml
  .github/workflows/CI.yml
  forunb/main/templates/main/questions.html
  requirements.txt
Labels: DevOps

#87 71 desenvolver um web scraping
  forunb/main/management/commands/scraping_sigaa.py
  forunb/main/migrations/0003_alter_forum_description.py
  forunb/main/models.py
  forunb/main/scraping.py
  forunb/main/sessions.py
Labels: enhancement, back-end

#88 70 pagina do forum
  forunb/forunb/settings.py
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/question_detail.html
  forunb/main/templatetags/_init_.py
  forunb/main/templatetags/custom_filters.py
  forunb/main/views.py
  forunb/static/css/styles.css
Labels: front-end

#86 65 implementacao do dockerr
  .github/workflows/CI.yml
  Dockerfile
  Makefile
  forunb/forunb/settings.py
  forunb/main/tests/test_forms.py
  requirements.txt
Labels: devops

#94 BugFix: Fixing creating new answer (html)
  forunb/main/templates/main/question_detail.html
Labels: front-end

#91 69-pagina-listagem-de-foruns
  forunb/main/templates/main/base.html
  forunb/main/templates/main/forums.html
Labels: front-end

#95 docs: adding sprint 7 in mkdocs
  docs/sprints/sprint7.md
  mkdocs.yml
Labels: documentation

#96 Estudo
  docs/sprints/Sprint6.md
  docs/sprints/sprint7.md
  mkdocs.yml
Labels: documentation

#97 Development
  .github/workflows/CI.yml
  Dockerfile
  Makefile
  README.md
  forunb/forunb/settings.py
  forunb/main/management/commands/scraping_sigaa.py
  forunb/main/migrations/0003_alter_forum_description.py
  forunb/main/models.py
  forunb/main/scraping.py
  forunb/main/sessions.py
  forunb/main/templates/main/base.html
  forunb/main/templates/main/forum_detail.html
  forunb/main/templates/main/forums.html
  forunb/main/templates/main/question_detail.html
  forunb/main/templates/main/questions.html
  forunb/main/templatetags/_init_.py
  forunb/main/templatetags/custom_filters.py
  forunb/main/tests/test_forms.py
  forunb/main/tests/test_models.py
  forunb/main/tests/test_url.py
  forunb/main/tests/test_views.py
  forunb/main/views.py
  forunb/static/css/styles.css
  requirements.txt
Labels: front-end, back-end, devops, docker

#99 docs: fixing name
  docs/sprints/sprint6.md
Labels: documentation

#100 Estudo
  docs/sprints/sprint6.md
Labels: documentation

#111 101 desenvolver novo model de user e personaliza lo
  forunb/forunb/settings.py
  forunb/main/forms.py
  forunb/main/tests/test_forms.py
  forunb/main/tests/test_models.py
  forunb/main/tests/test_views.py
  forunb/main/urls.py
  forunb/users/admin.py
  forunb/users/forms.py
  forunb/users/migrations/0001_initial.py
  forunb/users/migrations/0002_customuser_created_answers_and_more.py
  forunb/users/migrations/0003_alter_customuser_username.py
  forunb/users/models.py
  forunb/users/tests.py
  forunb/users/urls.py
  forunb/users/views.py
Labels: back-end

#113 72 barra de pesquisa 1
  forunb/forunb/settings.py
  forunb/forunb/urls.py
  forunb/main/templates/main/base.html
  forunb/main/templates/main/forums.html
  forunb/main/tests/test_views.py
  forunb/search/__init__.py
  forunb/search/admin.py
  forunb/search/apps.py
  forunb/search/migrations/__init__.py
  forunb/search/models.py
  forunb/search/templates/search/not_found.html
  forunb/search/urls.py
  forunb/search/views.py
Labels: back-end

#117 refactor: updating scraping
  forunb/main/management/commands/scraping_sigaa.py
Labels: back-end
